## config context path to "/" by setting an empty string
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  pid:
    file: agenspop.pid
  main:
    banner-mode: "off"
  resources:
    cache:
      period: 3600
    static-locations: classpath:/resources/,classpath:/static/
  groovy:
    template:
      check-template-location: false

agens:
  api:
    base-path: /api
    query-timeout: 600000       # 1000 ms = 1 sec
  elastic:
    host: localhost
    port: 9300
    cluster-name: es-bitnine
    page-size: 2500
  product:
    name: agenspop-es
    version: 0.7-dev
    hello-msg: agenspop-elasticsearch v1.0 (since 2019-08-01)
  drivers:
    #path: ./drivers
    path: classpath:bin
    jars:
      pgsql: postgresql-42.2.5.jar
      mysql: mysql-connector-java-5.1.47-bin.jar
